export const Roles = {
  PROJECT_COORDINATOR: "PROJECT_COORDINATOR",
  MEMBER: "MEMBER",
  EXAMINER: "EXAMINER",
  SUPERVISOR: "SUPERVISOR",
  CO_SUPERVISOR: "CO_SUPERVISOR",
  PROJECT_LEADER: "PROJECT_LEADER",
  STAFF: "STAFF",
  STUDENT: "STUDENT",
};
